version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "2323:2323"
    networks: 
      - login-crud-app

  mongodata:
    image: mongo
    networks: 
      - login-crud-app

networks: 
  login-crud-app:
    driver: bridge