version: "3"

services: 
  web:
    container_name: crud-app
    restart: always
    build: .
    ports: 
      - "2323:3000"
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app
    networks:
      - login-crud-app

  mongo:
    container_name: mydatabase
    image: mongo
    ports: 
      - "27018:27017"
    networks:
      - login-crud-app

networks: 
  login-crud-app:
    driver: bridge

# version: "3"
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports: 
#       - "2323:2323"
#     networks: 
#       - login-crud-app

#   mongodata:
#     image: mongo
#     networks: 
#       - login-crud-app

# networks: 
#   login-crud-app:
#     driver: bridge