version: "3"
services:
  app:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://db:27017/redSocial

  db:
    image: mongo:4.2
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - app-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /db/data
      o: bind

networks:
  app-network:
    driver: bridge
