version: "3"
services:
    mongo:
        container_name: mongo
        image: mongo
        volumes: 
            - /data/db:/var/lib/mongodb/data/db
        ports: 
            - "27017:27017"
    web:
        image: node-red-social
        container_name: app
        build: .
        ports: 
            - "2323:2323"
        restart: on-failure 
        depends_on: 
            - mongo